name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Test
        uses: cypress-io/github-action@v1
        with:
          start: yarn dev
          wait-on: "http://localhost:3000"
